"""The posting calendar.

PLAN is generated — do not hand-edit it. Regenerate with:

    python tools/build_posting_plan.py --weeks 26

RECURRING has no end date on purpose. When PLAN runs out, or has nothing for
today, RECURRING still fires. A dated calendar that quietly expires is how an
account goes dark for months without ever raising an error.
"""

from __future__ import annotations

from typing import Dict, List

# --- Recurring floor. No end date. Never delete this. ---------------------
RECURRING: List[Dict[str, str]] = [
    {"weekday": "tue", "time": "20:00", "type": "overheard"},
    {"weekday": "thu", "time": "21:00", "type": "overheard"},
    {"weekday": "sun", "time": "19:00", "type": "overheard"},
]

# --- Dated calendar. Generated by tools/build_posting_plan.py -------------
# BEGIN GENERATED PLAN
PLAN: List[Dict[str, str]] = [
    {"date": "2026-08-16", "time": "19:00", "type": "overheard"},
    {"date": "2026-08-18", "time": "20:00", "type": "overheard"},
    {"date": "2026-08-20", "time": "21:00", "type": "overheard"},
    {"date": "2026-08-23", "time": "19:00", "type": "overheard"},
    {"date": "2026-08-25", "time": "20:00", "type": "overheard"},
    {"date": "2026-08-27", "time": "21:00", "type": "overheard"},
    {"date": "2026-08-30", "time": "19:00", "type": "overheard"},
    {"date": "2026-09-01", "time": "20:00", "type": "overheard"},
    {"date": "2026-09-03", "time": "21:00", "type": "overheard"},
    {"date": "2026-09-06", "time": "19:00", "type": "overheard"},
    {"date": "2026-09-08", "time": "20:00", "type": "overheard"},
    {"date": "2026-09-10", "time": "21:00", "type": "overheard"},
    {"date": "2026-09-13", "time": "19:00", "type": "overheard"},
    {"date": "2026-09-15", "time": "20:00", "type": "overheard"},
    {"date": "2026-09-17", "time": "21:00", "type": "overheard"},
    {"date": "2026-09-20", "time": "19:00", "type": "overheard"},
    {"date": "2026-09-22", "time": "20:00", "type": "overheard"},
    {"date": "2026-09-24", "time": "21:00", "type": "overheard"},
    {"date": "2026-09-27", "time": "19:00", "type": "overheard"},
    {"date": "2026-09-29", "time": "20:00", "type": "overheard"},
    {"date": "2026-10-01", "time": "21:00", "type": "overheard"},
    {"date": "2026-10-04", "time": "19:00", "type": "overheard"},
    {"date": "2026-10-06", "time": "20:00", "type": "overheard"},
    {"date": "2026-10-08", "time": "21:00", "type": "overheard"},
    {"date": "2026-10-11", "time": "19:00", "type": "overheard"},
    {"date": "2026-10-13", "time": "20:00", "type": "overheard"},
    {"date": "2026-10-15", "time": "21:00", "type": "overheard"},
    {"date": "2026-10-18", "time": "19:00", "type": "overheard"},
    {"date": "2026-10-20", "time": "20:00", "type": "overheard"},
    {"date": "2026-10-22", "time": "21:00", "type": "overheard"},
    {"date": "2026-10-25", "time": "19:00", "type": "overheard"},
    {"date": "2026-10-27", "time": "20:00", "type": "overheard"},
    {"date": "2026-10-29", "time": "21:00", "type": "overheard"},
    {"date": "2026-11-01", "time": "19:00", "type": "overheard"},
    {"date": "2026-11-03", "time": "20:00", "type": "overheard"},
    {"date": "2026-11-05", "time": "21:00", "type": "overheard"},
    {"date": "2026-11-08", "time": "19:00", "type": "overheard"},
    {"date": "2026-11-10", "time": "20:00", "type": "overheard"},
    {"date": "2026-11-12", "time": "21:00", "type": "overheard"},
    {"date": "2026-11-15", "time": "19:00", "type": "overheard"},
    {"date": "2026-11-17", "time": "20:00", "type": "overheard"},
    {"date": "2026-11-19", "time": "21:00", "type": "overheard"},
    {"date": "2026-11-22", "time": "19:00", "type": "overheard"},
    {"date": "2026-11-24", "time": "20:00", "type": "overheard"},
    {"date": "2026-11-26", "time": "21:00", "type": "overheard"},
    {"date": "2026-11-29", "time": "19:00", "type": "overheard"},
    {"date": "2026-12-01", "time": "20:00", "type": "overheard"},
    {"date": "2026-12-03", "time": "21:00", "type": "overheard"},
    {"date": "2026-12-06", "time": "19:00", "type": "overheard"},
    {"date": "2026-12-08", "time": "20:00", "type": "overheard"},
    {"date": "2026-12-10", "time": "21:00", "type": "overheard"},
    {"date": "2026-12-13", "time": "19:00", "type": "overheard"},
    {"date": "2026-12-15", "time": "20:00", "type": "overheard"},
    {"date": "2026-12-17", "time": "21:00", "type": "overheard"},
    {"date": "2026-12-20", "time": "19:00", "type": "overheard"},
    {"date": "2026-12-22", "time": "20:00", "type": "overheard"},
    {"date": "2026-12-24", "time": "21:00", "type": "overheard"},
    {"date": "2026-12-27", "time": "19:00", "type": "overheard"},
    {"date": "2026-12-29", "time": "20:00", "type": "overheard"},
    {"date": "2026-12-31", "time": "21:00", "type": "overheard"},
    {"date": "2027-01-03", "time": "19:00", "type": "overheard"},
    {"date": "2027-01-05", "time": "20:00", "type": "overheard"},
    {"date": "2027-01-07", "time": "21:00", "type": "overheard"},
    {"date": "2027-01-10", "time": "19:00", "type": "overheard"},
    {"date": "2027-01-12", "time": "20:00", "type": "overheard"},
    {"date": "2027-01-14", "time": "21:00", "type": "overheard"},
    {"date": "2027-01-17", "time": "19:00", "type": "overheard"},
    {"date": "2027-01-19", "time": "20:00", "type": "overheard"},
    {"date": "2027-01-21", "time": "21:00", "type": "overheard"},
    {"date": "2027-01-24", "time": "19:00", "type": "overheard"},
    {"date": "2027-01-26", "time": "20:00", "type": "overheard"},
    {"date": "2027-01-28", "time": "21:00", "type": "overheard"},
    {"date": "2027-01-31", "time": "19:00", "type": "overheard"},
    {"date": "2027-02-02", "time": "20:00", "type": "overheard"},
    {"date": "2027-02-04", "time": "21:00", "type": "overheard"},
    {"date": "2027-02-07", "time": "19:00", "type": "overheard"},
    {"date": "2027-02-09", "time": "20:00", "type": "overheard"},
    {"date": "2027-02-11", "time": "21:00", "type": "overheard"},
]
# END GENERATED PLAN
